name: Check PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  javapos-workflow:
    uses: JavaPOSWorkingGroup/javapos-workflow/.github/workflows/check.yml@v2
    with:
      github-event-action: ${{github.event.action}}
    secrets: inherit
